### ISSUE TITLE
Add new response time stats to FAQs

### ISSUE THREAD

**Issue by benburwell** [MCEMS/www#1]
Our current response time stats are from 2013.

**Comment by benburwell** [comment]
@EliRuss, could you look into this? Not a priority, but it'd be nice at some point.

**Comment by EliRuss** [comment]
That is not information we have collected since that time, I believe. We should simply use the same time and include that we responded to 172 calls for service (including Medical Standby events) during the 2014-2015 academic year.

**Comment by benburwell** [comment]
Done in b0afb89ae773a02e9acc387b53fab396e7d53b15
