### ISSUE TITLE
Get new tech officer set up

### ISSUE THREAD

**Issue by benburwell** [MCEMS/www#10]
@NewtonianBrown, can you get Thomas set up with GitHub and show him how to edit the site? Let me know when he has a username and I'll add him to the organization.

Thanks!

**Comment by benburwell** [comment]
Maybe see if Ashley is interested as well?

cc: @EliRuss

**Comment by EliRuss** [comment]
Do we want to show the new Closed E-Board how to use GitHub? Or, do we want any Closed E-Board request to be passed onto the Technology Officer(s) who will utilized GitHub?

**Comment by benburwell** [comment]
That's up to you guys -- I think it'd at least be helpful for the tech officers. But if others are interested, I don't think it'd hurt. It's more just a matter of communicating effectively. If it's easier to communicate through the tech officers, that's fine with me! Maybe explain to the others what GitHub is and how it's being used and see what they want to do?

**Comment by EliRuss** [comment]
Ok, the Closed E-Board will figure it out tonight on our conference call, and I'll report back accordingly.

**Comment by EliRuss** [comment]
The Closed E-Board would like the Technology Officers (@NewtonianBrown) along with @jmankhan to give us a brief in the 3rd week of January timeframe on how to use GitHub as well as any other pertinent information.

**Comment by jeigen** [comment]
Tom now has a git hub, could you send him an invite (@benburwell).  his username is tyanushefski

**Comment by benburwell** [comment]
Sent the invite, you should be able to show him around the project now. Thanks!

**Comment by jeigen** [comment]
he's all sent up and will contact me if needs help before bothering you guys
