### ISSUE TITLE
Service Credit requests being forwarded via ems@muhlenberg.edu 

### ISSUE THREAD

**Issue by jeigen** [MCEMS/www#11]
@benburwell @jmankhan Service Credit request are currently being sent to everyone in ems through ems@muhlenberg.edu.  These request should be only go to the president and secretary.  Is it possible to look at this and change this.  

Justin

**Comment by benburwell** [comment]
These emails should not be getting sent to ems@muhlenberg.edu, and I can't find evidence of this happening in the logs. Could you forward me one that you've received so I can look into it?

**Comment by benburwell** [comment]
> From: "MCEMS" webmaster@bergems.org
> Date: January 24, 2016 at 12:00:18 AM EST
> To: je249474@muhlenberg.edu
> Subject: Service Credit Requested
> Reply-To: ems@muhlenberg.edu
> 
> A member has requested a service credit. Description:
> 
> Cleaning the truck off in the snow
> 1730-1800
> 
> Sign on to approve or reject.

Are you referring to the `Reply-To` header? That can definitely be changed. The emails are not being sent to everyone, though, they are sent to people who have the "Approve service credits" permission. If you want them to go only to the president and secretary, simply uncheck that box for everyone else. Here are the people with that permission currently:

![image](https://cloud.githubusercontent.com/assets/654419/12566220/886a2548-c386-11e5-9876-dab8b6289b29.png)

If you would like the `Reply-To` header changed, let me know and we can certainly do that.

**Comment by jeigen** [comment]
Thanks. Will get back after talk to board.

**Comment by jeigen** [comment]
everything is okay as it is.  Thanks
