### ISSUE TITLE
Specific Member Bio Page

### ISSUE THREAD

**Issue by tyanushefski** [MCEMS/www#13]
Hey Ben, would it be possible to create a specific page for adding the member bios? Similar to the announcements page, where I could just add the information and pictures with the right formatting and upload it to bergems? We have the pictures of all the members, and I can get the quick little blurbs from the members to add. I just want to see if it would be possible to get something moving on the bio page task. 

Thank you!

**Comment by benburwell** [comment]
This would definitely be possible. In fact, I have an idea of how to make it even easier. I'll try to get the framework set up this weekend.

**Comment by tyanushefski** [comment]
Hey Ben, just wanted to see if you had the time to work on the page? I have a lot of the member bios, and will get the pictures from Justin, so I would be able to start adding them soon.

**Comment by benburwell** [comment]
Wow, completely forgot about this. I think I'll have some time to get it up and running tomorrow night. Thanks for the reminder!

**Comment by benburwell** [comment]
I just created #14 to get the ball rolling. Going to go ahead and close this issue.
